 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

# Overall Accuracy is: 51.88 (result different from BLIP-2 paper due to different implementation and transformers version)

model:
  arch: pa_blip2_opt
  model_type: cl_vqa_coco_opt2.7b
  use_grad_checkpoint: False
  load_finetuned: False
  freeze_vit: True

  qformer_text_input: True

datasets:
  cl_coco_vqa: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 490
    text_processor:
        eval:
          name: "blip_question"
run:
  runner: runner_cl
  task: eca_q_vqa
  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  inference_method: "generate"
  prompt: "Question: {} Short answer:"

  # cl setting
  init_topic: 1
  topic_per_task: 1

  seed: 42
  output_dir: "output/BLIP2/VQA/Vqav2_ZeroShot"

  evaluate: True
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
